BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        BoxLayout:
            orientation: 'vertical'
            BoxLayout:
                Button:
                    text: 'Genesis'
                Button:
                    text: 'Genesis'
            BoxLayout:
                Button:
                    text: 'Genesis'
                Button:
                    text: 'Genesis'
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Exodus'
            Button:
                text: 'Leviticus'
            Button:
                text: 'Numbers'
    BoxLayout:
        size_hint_y: 0.1
        Button:
            text: 'Deuteronomy'
